### ISSUE TITLE
Leaking PooledMutableBlockPos

### ISSUE THREAD

**Issue by Cadiboo** [Gliby/physics#2]
https://github.com/Gliby/physics/blob/aac6f57047083a95ac990445edeeb9dc5eae0cf8/src/main/java/gliby/minecraft/physics/common/physics/engine/javabullet/JavaVoxelProvider.java#L62
By the time `blockPosition` is used in the `VoxelInfo`, it has been release and is likely to have been re-retained in another area of the game and moved somewhere else.
This can be solved by only releasing `blockPosition` in the `finalise` method of the `VoxelInfo` or using a non-pooled block pos

**Comment by Cadiboo** [comment]
Closed by 5edd29fe26168dfc6fd0d8c0ad630e398d76b970

**Comment by Gliby** [comment]
The issue has bee resolved in 5edd29fe26168dfc6fd0d8c0ad630e398d76b970.
Thanks.
