### ISSUE TITLE
NullPointerException after explosion

### ISSUE THREAD

**Issue by TimeConqueror** [Gliby/physics#3]
Crash when I tried to explode this structure:
![image](https://user-images.githubusercontent.com/25156941/77566207-64b71c00-6ed6-11ea-9840-839661390771.png)

After that world becomes inaccessible until mod is deleted.

[crash-2020-03-25_20.15.41-server.txt](https://github.com/Gliby/physics/files/4382381/crash-2020-03-25_20.15.41-server.txt)

**Comment by Gliby** [comment]
Thanks for the report @TimeConqueror. This has been fixed in https://github.com/Gliby/physics/commit/cdfc7fb5a13dc51f3899029c89bd9d596dfd1f9b.
