### ISSUE TITLE
Random freezing every few seconds after settting off an explosion

### ISSUE THREAD

**Issue by iliketheletterh** [Gliby/physics#5]
After I set off an explosion I can fly around and look at the blocks with 300fps. However every few seconds my framerate drops to zero. I tried using optifine and setting my graphical settings to their minimum and it seemed to have no effect. I also pulled up my task manager to see if it is putting any strain on the cpu/gpu and it was only an increase in usage of ~10%. I am running forge 1.12.2-14.23.5.2772.

**Comment by Gliby** [comment]
Thanks for the report. This confirms my suspicions, the issue is the new physics engine. There's a JNI call that gathers voxel info and it's causing hitching on the game tick. This issue can be solved by moving the physics tick off the of Minecraft game thread, which is something I'm working on doing.

**Comment by iliketheletterh** [comment]
> Thanks for the report. This confirms my suspicions, the issue is the new physics engine. There's a JNI call that gathers voxel info and it's causing hitching on the game tick. This issue can be solved by moving the physics tick off the of Minecraft game thread, which is something I'm working on doing.

Is there any older version which I could use to fix this issue or will I just have to wait for the update? Also, do you have any idea when the update might be out, or is it more up in the air?

**Comment by MarkJGx** [comment]
All the older versions are up on curseforge. You could also try enabling "UseJavaPhysics" in the config file.

**Comment by Gliby** [comment]
There are older versions of the mod out on curseforge. You can also try enabling "UseJavaPhysics" in the config file. No ETA on the multi-thread update.
